# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '16.0'
 
use_frameworks!
workspace 'Modularization'
 
target 'GameCatalogue' do
  # Pods for App
end

target 'Core' do
  project '../Core/Core'
end

target 'Detail' do
  project '../Detail/Detail'
end

target 'Favorite' do
  project '../Favorite/Favorite'
end

target 'Component' do
  project '../Component/Component'
end

target 'Home' do
  project '../Home/Home'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end

